### ISSUE TITLE
Coinduction in Agda

### ISSUE THREAD

**Issue by bixuanzju** [lastland/CoInduction-Study#1]
FYI, you can also check out coinduction in Agda (size types + copatterns), which is much nicer and principled. As far as I remember, coinduction in Coq is broken, computation does not preserve types, though I am not sure if things have changed recently. 

http://www2.tcs.ifi.lmu.de/~abel/popl13.pdf
http://www.cse.chalmers.se/~abela/jfp15.pdf

**Comment by lastland** [comment]
@bixuanzju Thanks for the reference! I will take a look!

I've also heard that many people in Coq community are now using [paco](http://plv.mpi-sws.org/paco/), which is also something I want to explore in this repo.
